app:
  name: diisco-backend
  services:
    - name: api
      type: web
      instance_type: nano
      regions:
        - fra
      ports:
        - port: 8000
          protocol: http
      env:
        - key: PYTHON_VERSION
          value: 3.11.9
      build:
        buildpack: python
      run_command: gunicorn app:app --bind 0.0.0.0:$PORT
